# This file was generated by GoReleaser. DO NOT EDIT.
cask "piper" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "b517d6119243cf5a273dc4084541295f5b31406b7bd5d1492264e294f3927952"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28eb7fb92539023ca3ec38c7b863220278fd4c4fa68e0b3e7d323fab102bd21d"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6b8e161da40e9c2ffbc497a0f5d58c5a27f418769197de7c2769a64da350651"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "605b80dd6bd270a014e78b70367f8c1f58cbd147960e168d083396447b9e57fa"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_linux_arm64.tar.gz"
    end
  end

  name "piper"
  desc "Stream any command's output live over HTTP"
  homepage "https://github.com/djalmaaraujo/piper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "piper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/piper"]
    end
  end

  # No zap stanza required

end
