# This file was generated by GoReleaser. DO NOT EDIT.
cask "piper" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ba19913271034edcd94977aab91e07ce9d1d78824e26e363e7f3338f46f45228"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e268e60c7b38fe0683128f71a6d280c539ddfde39328aa82ab0eab41421543d5"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "122b7a52ebe6216f8e07c0e8541195047bee288c5fc82ce1eb0061f9c565faa9"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29b2ee3cadeac69cc5fdf9239808a150575034a8fdf5926a230fe78e04a0a6ca"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_linux_arm64.tar.gz"
    end
  end

  name "piper"
  desc "Stream any command's output live over HTTP"
  homepage "https://github.com/djalmaaraujo/piper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "piper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/piper"]
    end
  end

  # No zap stanza required

end
