# This file was generated by GoReleaser. DO NOT EDIT.
cask "piper" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "5b2258c8f608452f6db21f23412d96688d6257c617fa07f9ca087a48d3026f49"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2138b218ededa7d9f26eec7d2d48a622fce22af5fa847976f74c2e10807d1850"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ce482e07e8bfacadb9104e1a7825d1920d053bf5892910e24465aa4b20a8aa8"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "584066c814ecb9ffa1de920473ec63cc4544b3b6d3be75c5cb8bc6d732f19805"
      url "https://github.com/djalmaaraujo/piper/releases/download/v#{version}/piper_linux_arm64.tar.gz"
    end
  end

  name "piper"
  desc "Stream any command's output live over HTTP"
  homepage "https://github.com/djalmaaraujo/piper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "piper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/piper"]
    end
  end

  # No zap stanza required

end
